# Конфигурация линтера Clippy для проекта CPU Optimized App

# Файл конфигурации линтера Clippy для проекта CPU Optimized App.
# Этот файл содержит настройки для обеспечения качества кода:
#
# Общие настройки:
#   - Настроены пороговые значения для сложности типов, когнитивной
#     сложности и количества аргументов функций
# Разрешенные исключения:
#   - Разрешено использование unsafe кода, что необходимо для работы
#     с динамическими библиотеками
#   - В тестах разрешено использование unwrap(), expect() и panic!()
# Предупреждения:
#   - Настроены предупреждения о сложных типах, большом количестве
#     аргументов и высокой когнитивной сложности
#   - Предупреждения о неиспользуемых импортах, переменных и
#     результатах
# Запреты:
#   - Запрещено использование устаревших функций
#   - Запрещено использование неправильных атрибутов, типов и
#     конструкций
#   - Эта конфигурация поможет поддерживать высокое качество кода в
#     проекте, обеспечивая соблюдение лучших практик программирования
#     на Rust.

# Настройка пороговых значений
too-many-arguments-threshold = 8
type-complexity-threshold = 250
cognitive-complexity-threshold = 25
doc-valid-idents = ["CPU", "AVX", "AVX2", "SSE", "NEON", "ARM"]

# Отключение некоторых проверок
disallowed-names = []
